import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const YOUTUBE_PLAYLIST_ITEMS_API = 'https://www.googleapis.com/youtube/v3/playlistItems';

export async function getServerSideProps() {
  const res = await fetch(`${YOUTUBE_PLAYLIST_ITEMS_API}?part=snippet&maxResults=2&playlistId=PLbu_fGT0MPsu_H1p1UdlJYgSff-chZZEZ&key=${process.env.YOUTUBE_API_KEY}`)

  
  const data = await res.json();
  return {
    props: {
      data
    }
  }
}


export default function Home({data}) {
  console.log('data', data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Playlists
        </h1>



        <ul className={styles.grid}>
        {data.items.map(({ id, snippet = {} }) => {
        const { title, thumbnails = {}, resourceId = {} } = snippet;
        const { medium } = thumbnails;
        return (
          <li key={id} className={styles.card}>
            <a href={`https://www.youtube.com/watch?v=${resourceId.videoId}`}>
              <p>
                <img width={medium.width} height={medium.height} src={medium.url} alt="" />
              </p>
              <h3>{ title }</h3>
            </a>
          </li>
        )
      })}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
